In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('50_Startups.csv')

In [3]:
data.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [5]:
features = data.iloc[:,[0,1,2,3]].values
label = data.iloc[:,4].values

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
oheState = OneHotEncoder(sparse_output=True)

dummyState = oheState.fit_transform(features[:,3].reshape(-1,1)).toarray()

In [11]:
dummyState

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [12]:
final_features = np.concatenate((dummyState,features[:,[0,1,2]]),axis=1)

In [13]:
final_features

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [0.0, 1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 0.0, 1.0, 86419.7, 153514.11, 0.0],
       [1.0, 0.0, 0.0, 76253.86, 113867.3, 298664.47],
       [0.0, 0.0, 1.0, 78389.47, 153773.43, 299737.29],
       [0.0, 1.0, 0.0, 73994.56, 122782.75, 303319.26],
       [0.0, 1.0, 0.0, 67532.53, 105751.03, 304768.73],
       [0.0, 0.0, 1.0, 77044.01, 99281.34, 140574.81],
       [1.0, 0.0, 0.0, 64664.71, 139553.16, 137962.62],
       [0.0, 1.0, 0.0, 75328.87, 144135.98, 134050.07],
       [0.0, 0.0, 1.0, 72107.6, 127864.55, 353183.81],
       [0.0, 1.0, 0.0, 66051.52, 182645.56, 118148.2],
       [0.0, 0.0, 1.0, 65605.48, 153032.06, 107138.38],
       [0.0, 1.0, 0.0, 61994.48, 115641.28, 91131.24],
       [0.0, 0.0, 1.0, 61136.38, 152701.92, 88218.23],
       [1.0, 0.0, 0.0, 63408.86, 129219.61, 46085.25],
       [0.0, 1.0, 0.0, 55493.95, 103057.49, 214634.81],
       [1.0, 0.0, 0.0, 46426.07, 157693.92, 210797.67],
       [0.0, 0.0, 1.0, 46014.02, 85047.44, 205517.64],
       [0.0, 1.0, 0.0, 28663.76, 127056.21, 201126.82],
       [1.0, 0.0, 0.0, 44069.95, 51283.14, 197029.42],
       [0.0, 0.0, 1.0, 20229.59, 65947.93, 185265.1],
       [1.0, 0.0, 0.0, 38558.51, 82982.09, 174999.3],
       [1.0, 0.0, 0.0, 28754.33, 118546.05, 172795.67],
       [0.0, 1.0, 0.0, 27892.92, 84710.77, 164470.71],
       [1.0, 0.0, 0.0, 23640.93, 96189.63, 148001.11],
       [0.0, 0.0, 1.0, 15505.73, 127382.3, 35534.17],
       [1.0, 0.0, 0.0, 22177.74, 154806.14, 28334.72],
       [0.0, 0.0, 1.0, 1000.23, 124153.04, 1903.93],
       [0.0, 1.0, 0.0, 1315.46, 115816.21, 297114.46],
       [1.0, 0.0, 0.0, 0.0, 135426.92, 0.0],
       [0.0, 0.0, 1.0, 542.05, 51743.15, 0.0],
       [1.0, 0.0, 0.0, 0.0, 116983.8, 45173.06]], dtype=object)

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [16]:
for i in range(1,301):
    for depth in range(3,11):
        x_train,x_test,y_train,y_test = train_test_split(final_features,label,test_size=0.2,random_state=i)
        
        model = RandomForestRegressor(
            n_estimators=5,
            max_depth=depth,
            random_state=2
        )
        
        model.fit(x_train,y_train)
        
        trainScore = model.score(x_train,y_train)
        testScore = model.score(x_test,y_test)
        
        if testScore>trainScore and testScore >=0.9:
            print(f"Test {testScore} | Train {trainScore} and rs {i} | depth {depth}")

Test 0.9579400372866264 | Train 0.9521175702589892 and rs 51 | depth 3
Test 0.96149256460898 | Train 0.9537113213257995 and rs 119 | depth 3
Test 0.9694324062169338 | Train 0.9610723949912325 and rs 119 | depth 4
Test 0.9720153964192707 | Train 0.9614975892931061 and rs 119 | depth 5
Test 0.9740242156097941 | Train 0.9639092952311936 and rs 119 | depth 6
Test 0.9733460772177368 | Train 0.962658840386073 and rs 119 | depth 7
Test 0.9730512848916928 | Train 0.9627332519645545 and rs 119 | depth 8
Test 0.9730512848916928 | Train 0.9627332519645545 and rs 119 | depth 9
Test 0.9730512848916928 | Train 0.9627332519645545 and rs 119 | depth 10
Test 0.9490407940274445 | Train 0.9410737710839897 and rs 128 | depth 3
Test 0.9477242915031288 | Train 0.9406180731688222 and rs 128 | depth 4
Test 0.9505817904753446 | Train 0.9385171224550379 and rs 128 | depth 5
Test 0.9508551194752124 | Train 0.9423719439605418 and rs 128 | depth 6
Test 0.9532446304392698 | Train 0.9418276632937647 and rs 128 | depth 7
Test 0.953478327026287 | Train 0.9417980901082985 and rs 128 | depth 8
Test 0.953478327026287 | Train 0.9417980901082985 and rs 128 | depth 9
Test 0.953478327026287 | Train 0.9417980901082985 and rs 128 | depth 10
Test 0.9737665523368094 | Train 0.9660490988023273 and rs 154 | depth 3
Test 0.9727116194581567 | Train 0.9682379075039945 and rs 154 | depth 4
Test 0.9818264162381104 | Train 0.9773719985661841 and rs 158 | depth 5
Test 0.9847343882937307 | Train 0.9782895430779058 and rs 158 | depth 6
Test 0.9836307370034988 | Train 0.9819324124656116 and rs 158 | depth 8
Test 0.9836307370034988 | Train 0.9819324124656116 and rs 158 | depth 9
Test 0.9836307370034988 | Train 0.9819324124656116 and rs 158 | depth 10
Test 0.9550368601122519 | Train 0.953033180994248 and rs 160 | depth 5
Test 0.9739779614848694 | Train 0.9590244962863169 and rs 162 | depth 4
Test 0.9663911678264766 | Train 0.9639617723551805 and rs 162 | depth 6
Test 0.9645669626530572 | Train 0.9526936564275507 and rs 188 | depth 5
Test 0.9736015910834948 | Train 0.973403166413734 and rs 209 | depth 4
Test 0.9745216395417096 | Train 0.9739884144620204 and rs 210 | depth 5
Test 0.9755566631417343 | Train 0.9738443103411416 and rs 210 | depth 7
Test 0.9755566631417343 | Train 0.9738443103411416 and rs 210 | depth 8
Test 0.9755566631417343 | Train 0.9738443103411416 and rs 210 | depth 9
Test 0.9755566631417343 | Train 0.9738443103411416 and rs 210 | depth 10
Test 0.965659798100149 | Train 0.9527130701286438 and rs 221 | depth 3
Test 0.9713345582677894 | Train 0.9638399905712323 and rs 221 | depth 5
Test 0.9704376614817138 | Train 0.964946397519531 and rs 221 | depth 7
Test 0.9722380259442601 | Train 0.970893324243325 and rs 221 | depth 8
Test 0.9722406791306939 | Train 0.9703779681478257 and rs 221 | depth 9
Test 0.9722406791306939 | Train 0.9703779681478257 and rs 221 | depth 10
Test 0.9811215672374138 | Train 0.9800221005191709 and rs 233 | depth 3
Test 0.9776392959751558 | Train 0.9717631289833382 and rs 271 | depth 5
Test 0.972888614983124 | Train 0.9672788801288558 and rs 271 | depth 6
Test 0.9746607958571492 | Train 0.969441334104168 and rs 271 | depth 7
Test 0.9746408512588097 | Train 0.9698606014246164 and rs 271 | depth 8
Test 0.9716005690262186 | Train 0.969336257990642 and rs 271 | depth 9
Test 0.9716005690262186 | Train 0.969336257990642 and rs 271 | depth 10
Test 0.9695843160704833 | Train 0.961971078801251 and rs 288 | depth 3

In [17]:
# Test 0.9818264162381104 | Train 0.9773719985661841 and rs 158 | depth 5
x_train,x_test,y_train,y_test = train_test_split(final_features,label,test_size=0.2,random_state=158)
model = RandomForestRegressor(
    n_estimators=5,
    max_depth=5,
    random_state=2
)

model.fit(x_train,y_train)

RandomForestRegressor(max_depth=5, n_estimators=5, random_state=2)

In [18]:
data.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
state = oheState.transform(np.array([['California']]))
state = state.toarray()

array([[1., 0., 0.]])

In [24]:
predict = model.predict(np.array([[1,0,0,20000,20000,20000]]))
predict

array([72382.90466667])