In [17]:
# https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv

In [18]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [21]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [22]:
df['variety'].unique()

array(['Setosa', 'Versicolor', 'Virginica'], dtype=object)

# Seprate feature and label

In [23]:
features = df.iloc[:,[0,1,2,3]].values
label = df.iloc[:,4].values

# Model building

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [25]:
for rs in range(1,301):
    x_train,x_test,y_train,y_test = train_test_split(features,label,test_size=0.2,random_state=rs)
    model = LogisticRegression(max_iter=1000)
    
    model.fit(x_train,y_train)
    
    trainScore = model.score(x_train,y_train)
    testScore = model.score(x_test,y_test)
    if testScore >= 0.9:
        print(f"Test Score {testScore} and Train Score {trainScore}, rs {rs}")

Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 1
Test Score 0.9666666666666667 and Train Score 0.975, rs 2
Test Score 1.0 and Train Score 0.9666666666666667, rs 3
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 4
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 5
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 6
Test Score 0.9 and Train Score 0.975, rs 8
Test Score 1.0 and Train Score 0.975, rs 9
Test Score 1.0 and Train Score 0.975, rs 10
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 11
Test Score 0.9666666666666667 and Train Score 0.975, rs 12
Test Score 0.9666666666666667 and Train Score 0.975, rs 13
Test Score 0.9666666666666667 and Train Score 0.975, rs 14
Test Score 1.0 and Train Score 0.975, rs 15
Test Score 0.9 and Train Score 0.9833333333333333, rs 16
Test Score 0.9666666666666667 and Train Score 0.975, rs 17
Test Score 1.0 and Train Score 0.9666666666666667, rs 18
Test Score 1.0 and Train Score 0.9666666666666667, rs 19
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 20
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 21
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 22
Test Score 1.0 and Train Score 0.9666666666666667, rs 23
Test Score 1.0 and Train Score 0.9666666666666667, rs 24
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 25
Test Score 0.9666666666666667 and Train Score 0.9583333333333334, rs 26
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 27
Test Score 0.9666666666666667 and Train Score 0.975, rs 28
Test Score 0.9 and Train Score 0.9833333333333333, rs 29
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 30
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 31
Test Score 1.0 and Train Score 0.9583333333333334, rs 32
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 33
Test Score 1.0 and Train Score 0.9666666666666667, rs 34
Test Score 1.0 and Train Score 0.9666666666666667, rs 35
Test Score 0.9666666666666667 and Train Score 0.975, rs 36
Test Score 1.0 and Train Score 0.975, rs 37
Test Score 1.0 and Train Score 0.9666666666666667, rs 38
Test Score 0.9666666666666667 and Train Score 0.975, rs 39
Test Score 1.0 and Train Score 0.9833333333333333, rs 40
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 41
Test Score 1.0 and Train Score 0.975, rs 42
Test Score 1.0 and Train Score 0.9666666666666667, rs 43
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 44
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 45
Test Score 0.9 and Train Score 0.9833333333333333, rs 46
Test Score 0.9666666666666667 and Train Score 0.9583333333333334, rs 47
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 48
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 49
Test Score 0.9666666666666667 and Train Score 0.975, rs 50
Test Score 0.9 and Train Score 0.975, rs 51
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 52
Test Score 0.9333333333333333 and Train Score 0.9916666666666667, rs 53
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 54
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 55
Test Score 0.9333333333333333 and Train Score 0.9916666666666667, rs 56
Test Score 1.0 and Train Score 0.95, rs 57
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 58
Test Score 1.0 and Train Score 0.9666666666666667, rs 59
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 60
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 61
Test Score 0.9333333333333333 and Train Score 0.975, rs 62
Test Score 0.9666666666666667 and Train Score 0.975, rs 63
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 64
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 65
Test Score 1.0 and Train Score 0.9666666666666667, rs 66
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 67
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 68
Test Score 0.9666666666666667 and Train Score 0.9583333333333334, rs 69
Test Score 1.0 and Train Score 0.9666666666666667, rs 70
Test Score 0.9666666666666667 and Train Score 0.975, rs 71
Test Score 1.0 and Train Score 0.9833333333333333, rs 72
Test Score 0.9666666666666667 and Train Score 0.975, rs 73
Test Score 1.0 and Train Score 0.9666666666666667, rs 74
Test Score 1.0 and Train Score 0.9583333333333334, rs 75
Test Score 0.9666666666666667 and Train Score 0.975, rs 76
Test Score 0.9333333333333333 and Train Score 0.9916666666666667, rs 78
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 79
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 80
Test Score 1.0 and Train Score 0.9666666666666667, rs 81
Test Score 0.9666666666666667 and Train Score 0.975, rs 82
Test Score 0.9 and Train Score 0.975, rs 83
Test Score 1.0 and Train Score 0.975, rs 84
Test Score 0.9666666666666667 and Train Score 0.9916666666666667, rs 85
Test Score 1.0 and Train Score 0.975, rs 86
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 87
Test Score 1.0 and Train Score 0.9833333333333333, rs 88
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 89
Test Score 0.9666666666666667 and Train Score 0.975, rs 90
Test Score 1.0 and Train Score 0.975, rs 91
Test Score 0.9 and Train Score 0.9916666666666667, rs 92
Test Score 1.0 and Train Score 0.9833333333333333, rs 93
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 94
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 95
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 96
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 97
Test Score 0.9333333333333333 and Train Score 0.9916666666666667, rs 98
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 99
Test Score 0.9666666666666667 and Train Score 0.975, rs 100
Test Score 1.0 and Train Score 0.9666666666666667, rs 101
Test Score 0.9666666666666667 and Train Score 0.975, rs 102
Test Score 1.0 and Train Score 0.975, rs 103
Test Score 1.0 and Train Score 0.9666666666666667, rs 104
Test Score 0.9666666666666667 and Train Score 0.975, rs 105
Test Score 1.0 and Train Score 0.975, rs 106
Test Score 1.0 and Train Score 0.975, rs 107
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 108
Test Score 0.9 and Train Score 0.9916666666666667, rs 109
Test Score 0.9666666666666667 and Train Score 0.975, rs 110
Test Score 0.9 and Train Score 0.9833333333333333, rs 111
Test Score 1.0 and Train Score 0.975, rs 112
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 113
Test Score 0.9 and Train Score 0.9833333333333333, rs 114
Test Score 0.9 and Train Score 0.975, rs 115
Test Score 0.9333333333333333 and Train Score 0.9916666666666667, rs 116
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 117
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 118
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 119
Test Score 1.0 and Train Score 0.9666666666666667, rs 120
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 121
Test Score 0.9666666666666667 and Train Score 0.975, rs 122
Test Score 1.0 and Train Score 0.9833333333333333, rs 123
Test Score 0.9 and Train Score 1.0, rs 124
Test Score 1.0 and Train Score 0.9666666666666667, rs 125
Test Score 1.0 and Train Score 0.975, rs 126
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 127
Test Score 1.0 and Train Score 0.975, rs 128
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 129
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 130
Test Score 0.9666666666666667 and Train Score 0.9583333333333334, rs 131
Test Score 0.9 and Train Score 0.9916666666666667, rs 132
Test Score 0.9666666666666667 and Train Score 0.9583333333333334, rs 133
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 134
Test Score 1.0 and Train Score 0.9666666666666667, rs 135
Test Score 0.9666666666666667 and Train Score 0.975, rs 136
Test Score 1.0 and Train Score 0.975, rs 137
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 138
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 139
Test Score 1.0 and Train Score 0.975, rs 140
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 141
Test Score 0.9333333333333333 and Train Score 0.975, rs 142
Test Score 0.9 and Train Score 0.9583333333333334, rs 143
Test Score 0.9666666666666667 and Train Score 0.975, rs 144
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 145
Test Score 0.9666666666666667 and Train Score 0.975, rs 146
Test Score 0.9 and Train Score 1.0, rs 147
Test Score 0.9666666666666667 and Train Score 0.95, rs 148
Test Score 1.0 and Train Score 0.9666666666666667, rs 149
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 150
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 151
Test Score 1.0 and Train Score 0.9666666666666667, rs 152
Test Score 0.9666666666666667 and Train Score 0.9583333333333334, rs 153
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 154
Test Score 1.0 and Train Score 0.9666666666666667, rs 155
Test Score 1.0 and Train Score 0.9666666666666667, rs 156
Test Score 0.9666666666666667 and Train Score 0.975, rs 157
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 158
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 159
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 160
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 161
Test Score 0.9666666666666667 and Train Score 0.975, rs 162
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 163
Test Score 0.9666666666666667 and Train Score 0.9583333333333334, rs 164
Test Score 1.0 and Train Score 0.9583333333333334, rs 165
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 166
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 167
Test Score 1.0 and Train Score 0.9666666666666667, rs 168
Test Score 1.0 and Train Score 0.975, rs 169
Test Score 1.0 and Train Score 0.975, rs 170
Test Score 0.9666666666666667 and Train Score 0.975, rs 171
Test Score 0.9 and Train Score 0.9833333333333333, rs 172
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 174
Test Score 0.9666666666666667 and Train Score 0.975, rs 175
Test Score 0.9 and Train Score 0.9666666666666667, rs 176
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 177
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 178
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 179
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 180
Test Score 0.9 and Train Score 0.9666666666666667, rs 181
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 182
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 183
Test Score 0.9666666666666667 and Train Score 0.975, rs 184
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 185
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 186
Test Score 1.0 and Train Score 0.9666666666666667, rs 187
Test Score 0.9666666666666667 and Train Score 0.95, rs 188
Test Score 1.0 and Train Score 0.975, rs 189
Test Score 0.9666666666666667 and Train Score 0.975, rs 190
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 191
Test Score 1.0 and Train Score 0.975, rs 192
Test Score 0.9666666666666667 and Train Score 0.975, rs 193
Test Score 0.9333333333333333 and Train Score 0.9583333333333334, rs 194
Test Score 1.0 and Train Score 0.9666666666666667, rs 195
Test Score 0.9 and Train Score 0.9916666666666667, rs 196
Test Score 1.0 and Train Score 0.9666666666666667, rs 197
Test Score 0.9666666666666667 and Train Score 0.9916666666666667, rs 198
Test Score 0.9333333333333333 and Train Score 0.975, rs 199
Test Score 1.0 and Train Score 0.9833333333333333, rs 200
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 201
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 202
Test Score 0.9333333333333333 and Train Score 0.975, rs 203
Test Score 0.9333333333333333 and Train Score 0.9583333333333334, rs 204
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 205
Test Score 0.9 and Train Score 0.9916666666666667, rs 206
Test Score 0.9333333333333333 and Train Score 0.9583333333333334, rs 207
Test Score 0.9666666666666667 and Train Score 0.975, rs 208
Test Score 0.9666666666666667 and Train Score 0.975, rs 209
Test Score 1.0 and Train Score 0.975, rs 210
Test Score 1.0 and Train Score 0.975, rs 211
Test Score 0.9333333333333333 and Train Score 0.975, rs 212
Test Score 1.0 and Train Score 0.9666666666666667, rs 213
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 214
Test Score 0.9666666666666667 and Train Score 0.975, rs 215
Test Score 0.9 and Train Score 1.0, rs 216
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 217
Test Score 0.9666666666666667 and Train Score 0.975, rs 218
Test Score 1.0 and Train Score 0.9666666666666667, rs 219
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 220
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 221
Test Score 0.9 and Train Score 0.9666666666666667, rs 222
Test Score 0.9666666666666667 and Train Score 0.975, rs 223
Test Score 1.0 and Train Score 0.975, rs 224
Test Score 0.9333333333333333 and Train Score 0.9916666666666667, rs 225
Test Score 1.0 and Train Score 0.9666666666666667, rs 226
Test Score 0.9333333333333333 and Train Score 0.975, rs 227
Test Score 1.0 and Train Score 0.975, rs 228
Test Score 0.9666666666666667 and Train Score 0.9583333333333334, rs 229
Test Score 0.9666666666666667 and Train Score 0.975, rs 230
Test Score 0.9666666666666667 and Train Score 0.975, rs 231
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 232
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 233
Test Score 1.0 and Train Score 0.975, rs 234
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 235
Test Score 0.9666666666666667 and Train Score 0.975, rs 236
Test Score 0.9666666666666667 and Train Score 0.975, rs 237
Test Score 0.9666666666666667 and Train Score 0.9916666666666667, rs 238
Test Score 0.9666666666666667 and Train Score 0.975, rs 239
Test Score 1.0 and Train Score 0.975, rs 240
Test Score 0.9666666666666667 and Train Score 0.975, rs 241
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 242
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 243
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 244
Test Score 0.9 and Train Score 0.9666666666666667, rs 245
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 246
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 247
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 248
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 249
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 250
Test Score 0.9333333333333333 and Train Score 0.9916666666666667, rs 251
Test Score 0.9 and Train Score 0.9833333333333333, rs 252
Test Score 0.9666666666666667 and Train Score 0.975, rs 253
Test Score 1.0 and Train Score 0.9666666666666667, rs 254
Test Score 0.9 and Train Score 0.975, rs 255
Test Score 1.0 and Train Score 0.975, rs 256
Test Score 1.0 and Train Score 0.975, rs 257
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 258
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 259
Test Score 1.0 and Train Score 0.9666666666666667, rs 260
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 261
Test Score 0.9666666666666667 and Train Score 0.975, rs 262
Test Score 1.0 and Train Score 0.975, rs 263
Test Score 0.9666666666666667 and Train Score 0.975, rs 264
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 265
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 266
Test Score 0.9333333333333333 and Train Score 0.9916666666666667, rs 267
Test Score 0.9 and Train Score 1.0, rs 268
Test Score 1.0 and Train Score 0.9666666666666667, rs 269
Test Score 1.0 and Train Score 0.975, rs 270
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 271
Test Score 0.9 and Train Score 0.975, rs 272
Test Score 1.0 and Train Score 0.9583333333333334, rs 273
Test Score 0.9 and Train Score 0.9833333333333333, rs 274
Test Score 0.9333333333333333 and Train Score 0.9916666666666667, rs 275
Test Score 0.9666666666666667 and Train Score 0.9583333333333334, rs 276
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 277
Test Score 1.0 and Train Score 0.975, rs 278
Test Score 0.9333333333333333 and Train Score 0.975, rs 279
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 280
Test Score 0.9333333333333333 and Train Score 0.975, rs 281
Test Score 0.9666666666666667 and Train Score 0.9833333333333333, rs 282
Test Score 0.9 and Train Score 0.975, rs 283
Test Score 1.0 and Train Score 0.975, rs 284
Test Score 0.9666666666666667 and Train Score 0.975, rs 285
Test Score 0.9666666666666667 and Train Score 0.975, rs 286
Test Score 0.9333333333333333 and Train Score 0.975, rs 287
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 288
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 289
Test Score 1.0 and Train Score 0.9666666666666667, rs 290
Test Score 1.0 and Train Score 0.975, rs 291
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 292
Test Score 1.0 and Train Score 0.975, rs 293
Test Score 1.0 and Train Score 0.975, rs 294
Test Score 0.9333333333333333 and Train Score 0.9833333333333333, rs 295
Test Score 0.9666666666666667 and Train Score 0.975, rs 296
Test Score 0.9666666666666667 and Train Score 0.9666666666666667, rs 297
Test Score 0.9333333333333333 and Train Score 0.9666666666666667, rs 298
Test Score 0.9666666666666667 and Train Score 0.9583333333333334, rs 299
Test Score 0.9666666666666667 and Train Score 0.975, rs 300

In [26]:
x_train,x_test,y_train,y_test = train_test_split(features,label,test_size=0.2,random_state=10)
model = LogisticRegression()

model.fit(x_train,y_train)

LogisticRegression()

In [33]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [35]:
predict = model.predict(np.array([[5.1,3.5,1.3,0.3]]))
predict

array(['Setosa'], dtype=object)